### ISSUE TITLE
In 'Get started' add general introduction

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/tiltIndicator#153]
@Tilmon please see the "Get started" article. It would be nice to start with a general introduction. I outlines a few questions that might spark some ideas about what to write, but feel free to write whatever you think might be useful. Most likely you have that text somewhere and would only need to paste it. 

You may paste the text below or add it directly and submit a pull request:

https://github.com/2DegreesInvesting/tiltIndicator/blob/main/inst/extdata/child/intro-general.Rmd

**Comment by AnneSchoenauer** [comment]
@Tilmon what do you think about this here: 

_tilt_ is a climate database that specifically targets smaller, medium-sized, and non-listed companies. The database so far includes four indicators that capture the carbon exposure of the products produced by the company and the pressure on the company to reduce emissions due to emission reduction targets in the sectors they operate in. These indicators can also be applied to the input products required by the companies to produce their products. 

The aim of these indicators is to provide a starting point for a set of indicators that can be used by banks for climate risk management, climate reporting, and climate action. These indicators can help guide companies in transitioning to a low-carbon economy, and enable banks to better manage climate risks associated with lending to these companies.
In the development of the indicators, there are five general approaches that we followed:  

**1. Most granular level of assessment.** tilt aims to assess climate-relevant information of companies at the most granular level possible. The most granular level we aim for is the product level. Once climate-relevant information is assessed on a product level, we aggregate this product level information to the company level. It depends on the indicator, whether an assessment on a product level before aggregation is suitable.
**2. Bottom-up approach.** tilt uses a bottom-up approach by assessing small and medium size (non-listed) companies. Following this, it fills the gap for climate assessment of companies as currently most data and rating providers focus on listed companies or larger non-listed companies.
**3. Automatization.** tilt aims at generating solutions in the most automated way possible, i.e., having solutions that require as little input from the banks as necessary. Furthermore, when matching and collecting the data, we aim for as little manual work as possible. When not possible, e.g., in the process of matching different databases, we will use a hybrid matching process. Quality is assured by manual checks. 
**4. Publicly available information.** tilt gathers publicly available information from companies, such as information shared from companies on B2B platforms and their websites. The publicly available information is then matched with other data sources that are open-source or non-profit.  
**5. No black box models.** tilt follows the principle of transparency. tilt provides detailed information on our data sources and the methodology of the indicators. The information will be publicly available and free to access.

_tilt_  (under the Programme name PASTAX) has received funding from the LIFE Programme of the European Union, as well as from xx. (@Tilmon could you please have a look if we need to mention Moore's foundation and ECF? As well as see if we need to pulbish the logo?)

@maurolepore: let @Tilmon respond to this first and if he agrees with it, we can add it to the get started article! Thanks both of you!

**Comment by AnneSchoenauer** [comment]
Here we are: https://docs.google.com/document/d/1Z4UbuqfAJVBz-mWQLa8DdDltOWiWx-Br/edit# (page 2)

**Comment by Tilmon** [comment]
@AnneSchoenauer thanks a lot! Will look at it tomorrow, once I'm done with data prep :)

**Comment by maurolepore** [comment]
Closing as it doesn't seem like a priority for now.
