### ISSUE TITLE
T5 Adjust scenario selection for output table in ISTR & PSTR

### ISSUE THREAD

**Issue by Tilmon** [2DegreesInvesting/tiltIndicator#168]
Dear @maurolepore and @kalashsinghal , 

this is a task related to the ISTR & PSTR indicator and I wonder whether this is something that should be done in the indicator or rather in the data prep or output file cleaning process: 

After we now included noth WEO & IPR scenarios in the real data, we need to make a selection of which scenarios to show in the final output. We should only show the following 4 scenarios: 
1) IPR RPS 2030 
2) IPR 2050 
3) WEO NZE 2030 
4) WEO NZE 2050

If it's easy to set a filter in the indicator output, might be elegant to do so. Otherwise, I can also pre-filter the input data so that you don't have to worry about. Let me know what you would prefer.

**Comment by maurolepore** [comment]
I think the simplest strategy is to process a single scenario at the time. The user can iterate over any number of scenarios with `lapply()` or a `for()` loop. 

This is different to the approach we took when we drafted the code for PSTR with the new data, where we iterated inside the PSTR code. That was hard and likely prone to errors, so I think this strategy is much better.  

In any case I'm pretty sure we wouldn't be able to compute multiple companies in memory because the data grows fast and saturates the memory. So we'll need to iterate anyway, and iterating over scenarios seems to make a lot of scense. 

To be sure I'll need to adapt the draft. But if that works, it would mean that we could close this issue and maybe replace it with an article showing how to iterate over multiple scenarios (and likely over chunks of companies).

**Comment by maurolepore** [comment]
See https://github.com/2DegreesInvesting/tiltIndicator/issues/118

**Comment by Tilmon** [comment]
Hi @maurolepore , good for me. Just a question: Would it be better for you if I pre-filtered already the relevant scenarios in the data prep? This would reduce the amount of computation power needed to calculate the indicators I guess. If that's correct, no problem for me to adjust.
