### ISSUE TITLE
In datasheet `tr_companies_all_230531` sectors and sub-sectors are seperated with `;` which should have a seperated row

### ISSUE THREAD

**Issue by AnneSchoenauer** [2DegreesInvesting/tiltIndicator#395]
**Aim**
I want to understand the total number of companies per our `tilt_sectors` and` tilt_subsectors`. So I want to create such a graph as an example: 
![image](https://github.com/2DegreesInvesting/tiltIndicator/assets/115623567/769555d4-39a2-4325-9563-e0a151c621d7)

**Problem**
The sheet [tr_companies_all_230531](https://drive.google.com/drive/folders/15lJ7tfH0KRB4mU0us7XUTBvpuo3MzxRU) has some rows in which there is no `clustered`, so `NA` but it has some information in which `tilt sector`  and `sub sector` the company operates. For example in row 21 the company 07-schanksysteme-gmbh_00000005076936-001 has the following `sector`: `Other; Land Use` plus `sub-sector`: `Other; Agriculture and Livestock; Food Related Products`. In that case there is one row with all the associated sectors to this company but as explained above the `clustered` are `NAs.`  Please note that I am not quite sure why we don't have any `clustered` and it might relate somehow to this [issue](https://github.com/2DegreesInvesting/tiltIndicator/issues/362). But for now I would like to concentrate on the sectors because my aim is for now only a graph like the above. However, we should also look into it why `clustered` has `NAs`.  

**First solution**
@ysherstyuk your solution ot this problem was the following. You loaded in the above sheet 
```
## Read the data
# Raw company data with products
tilt_companies_processed <- read_csv("data/tr_companies_all.csv")
```
and then you loaded in a sector mapper. Please note I used this one [here](https://docs.google.com/spreadsheets/d/1ER0vFyyLan6OB3kG6r40-oJq1SUotk5-cvtVksnzwT4/edit#gid=209597130). Here is also a screenshot to understand the problem straight-away: 
![image](https://github.com/2DegreesInvesting/tiltIndicator/assets/115623567/f86dc440-d66d-4cdc-8fb3-b7b5b0b7335b)

You then did the following (I added the description to the code to understand what you did)

As mentioned some sectors and sub-sectors are still seperated with a ";". To give each sector and subsector one row, we delimited it.

```{r}
# Split sectors
companies_split_sector <-tilt_companies_processed |>
  separate_rows(tilt_sector, sep="; ")

# Split subsectors
companies_split_subsector <- companies_split_sector|>
  separate_rows(tilt_subsector, sep="; ")

```

We now match it with the sector so that the right combination between sector and sub-sectors are in the columns.

```{r}
# Merging with the mapper
companies_split_subsector_filtered <- companies_split_subsector |>
  inner_join(sector_mapper, by = c('tilt_sector' = 'tilt_sector', 'tilt_subsector' = 'tilt_subsector'))
```

**Problem with the solution**
Please note that apparently some companies fall out after this process. The reason is that we have some sector combinations in our tilt_companies_processed datasheet that is not covered by the sector mappers. Therefore, they just fall out. 

See: 
The total number of companies for data of the sheet `tr_companies_all_230531` is **287978**:
```{r}
# N of companies in total
n_total_companies <- n_distinct(tilt_companies_processed$companies_id)
n_total_companies
```

But the total number of companies that was build with the sector mapper is **248513**: 
```{r}
# N of companies in total
n_total_companies <- n_distinct(companies_split_subsector_filtered$companies_id)
n_total_companies
```

Let's see where this comes from: 
```{r}
# Perform an anti-join to find unmatched combinations
unmatched_companies <- anti_join(companies_split_subsector, sector_mapper, by = c('tilt_sector', 'tilt_subsector'))
```
```{r}
# Get all unique combinations and view them
unique_combinations <- unmatched_companies %>%
  select(companies_id, tilt_sector, tilt_subsector) %>%
  unique()

# View the unique combinations
unique_combinations
```

The unique combinations look like the following: 
<img width="614" alt="image" src="https://github.com/2DegreesInvesting/tiltIndicator/assets/115623567/61b6ddc6-20c0-474e-ba93-335ad6c4d8f3">
Now as you can see from the above there are many combinations that the sector mappers don't cover. For example, automotive (tilt sector) with the sub_sector transportation, just don't exists in our sector mappers. Now the problem is that about 40,000 companies fall out as they have a weird sector and sub_sector combination. And my question is - is that correct? 

@Tilmon Do you know why this is the case? Or do you have a supposition because of the sector mapper generation? 
@ysherstyuk Can it be that in the process of delimiting the sectors and sub-sectors it can create random combinations?

**Comment by ysherstyuk** [comment]
Hi @AnneSchoenauer, thank you for checking in detail the solution and raising an issue here! @Lyanne and I looked in the script to verify this. The conclusion is that first of all, the process of delimitation does not create random combinations of sectors and subsectors. The split is made in the way that for every single sector, a row of a company is created, making sure for every row, there is only one sector mentioned and the same for subsectors. After all possible combinations, we join the dataset with the mapper that you shared with us. So indeed in the case there is for example Land Use as a tilt_sector and NA as a tilt_subsector as there is no match with the mapping table, the company indeed falls out because the match is not found. So that needs to be adjusted in the mapper in order to keep a company in the dataset.

**Comment by AnneSchoenauer** [comment]
@ysherstyukthanks a lot for this! Thanks for looking into it again and I understood your answer. @Tilmon do you put this on the list for this week's sprint? Thanks a lot!

**Comment by Tilmon** [comment]
Hi @AnneSchoenauer and @ysherstyuk I think to detect all potential sources for this problem, I would need to see the script + data you used. @AnneSchoenauer , you are referring to a "sector mapper" but only linked the [tilt-sector-subsector classification](https://docs.google.com/spreadsheets/d/1ER0vFyyLan6OB3kG6r40-oJq1SUotk5-cvtVksnzwT4/edit#gid=209597130) instead of a mapper. This is not clear to me. 
However, there are already 2 things I can point out: 

1. As we figured out, the sector mappers still have some weaknesses, so before calculating final results for a research paper I suggest to wait until the sector mappers are revised. This will be more effective than for every small issue trying to adapt the sector mappers accordingly. 
2. Due to an issue with the tilt-scenario-mapper, in the data prep, I removed the 3 `tilt_subsectors `from the `tilt_sector `landuse and replaced them with `NA `(Because IPR also does not have any land use sub-classifications). This is not reflected in the current Google Sheet version of the mapper yet (hence refactoring of data prep needed and in parallel revision of sector classifications and mappers). But still, this might lead to the problem that you can't map the `tilt_sector == land use & tilt_subsector == NA` combination, because it doesn't exist in the current mapper in the Google Sheet. To identify potential sources for the issue with the transportation or construction secotrs, I would need to see the actual script & data. 
If you still need clarification on this, @ysherstyuk or @AnneSchoenauer please either share all that with me OR schedule a call with me to walk me through what you did.

**Comment by Tilmon** [comment]
@AnneSchoenauer depending on data prep re-factoring, we might just eliminate the ";" in the sector columns as part of the data prep. This would solve the problem already I guess and you wouldn't need to fix it afterwards.

**Comment by Tilmon** [comment]
@bobresink @ysherstyuk FYI, I put this ticket on BLOCKED as it probably will be solved as part of the data preparation refactoring anyways.
