### ISSUE TITLE
Review Tilman's data prep code

### ISSUE THREAD

**Issue by Tilmon** [2DegreesInvesting/tiltIndicator#412]
Dear Bob, @maurolepore , @kalashsinghal ,  (@ysherstyuk you did the following already but I want to keep you in the loop)

as we were facing many issues with the data preparation scripts in the past, we need to refactor them. To plan that accordingly, I would kindly ask you three to block a few hours or even one day in the first half of next week too review my script to get an understanding of the exercise. 

As an intro into the problem, please find a broad overview of how data are connected and which data I used here: https://docs.google.com/presentation/d/1uVoGyWfYm2iQcRuj304zK8Bje6dhLQHe/edit#slide=id.p2

After that, you can find my data prep script here (v6 is the latest): https://drive.google.com/drive/u/0/folders/15lJ7tfH0KRB4mU0us7XUTBvpuo3MzxRU

The README file should bring some clarity on the purpose of different folders and scripts. In the scripts, there are some explanations but I am afraid they are not sufficient for you to understand all the context completely. 

I think this should be the following procedure: 

1. You review the code (take max 1 day to get a first overview first half next week)
2. When I am back on Thu or Fri, we agree together on what the best way is to proceed. 
3. End of next week, we should have a clear plan regarding responsibilities and timing. 

Thank you!
Tilman

**Comment by Tilmon** [comment]
Dear @maurolepore could you kindly also assign Bob to this issue and tag him in the description? For some reason, I can't assign him...

**Comment by maurolepore** [comment]
@Tilmon, I added @bobresink to the teams tilt and tilt-indicator. That makes him appear in the assignee list. I added him as you requested. 

However, Yana and Mirja alrady reviewed it, and now we're assigning it to Bob, Kalash, and me. So five people x 1 day is 5 work days. Do we need so much effort?

I don't think more reviews will have an effect on the approach. The approach is always the same, just like we did with the MVPs for the tiltIndicator: Engage with the code and the code author in a painful, systematic process where we first make the code reproducible from an executable script, then capture key outputs, then refactor the code ensuring the output doesn't change, then modularize the code and write finer level tests, then find bugs discuss them and fix them until we're comfortable.

**Comment by maurolepore** [comment]
@Tilmon 

I reviewed the code you shared. In general the task is the same as with the MVPs and the approach to I mentioned above is valid. But before  we get to that we first need to split the data_prep_v6/ project in sub-projects (a.k.a. "modules" see https://en.wikipedia.org/wiki/Modularity).

Condider these modular projects with focused, sequential goals:

1. tiltIndicatorBefore: Prepare tiltIndicator inputs.
2. tiltIndicator: Calculate tilt indicators.
3. tiltIndicatorAfter: Polish tiltIndicator outputs.

The data_prep_v6 project mixes goals 1 and 3. I suggest we reorganize the files and folders into two subdirectories -- tiltIndicatorBefore and tiltIndicatorAfter -- and focus first on tiltIndicatorBefore.

This structure allows using standard names for files and folders because the name of each focused project provides the context you need to know what to expect in each. 

For example, consider the following files and folders:

```
a. tiltIndicatorBefore/
     README.Rmd
     input/data.csv
     output/result.csv
     R/code.R

b. tiltIndicator/
     README.Rmd
     input/data.csv
     output/result.csv
     R/code.R

c. tiltIndicatorAfter/
     README.Rmd
     input/data.csv
     output/result.csv
     R/code.R
```

Although the three projects have the same files and folders, it's clear that tiltIndicatorBefore/output/result.csv is the same as tiltIndicator/input/data.csv and different and different to tiltIndicatorAfter/output/result.csv. It's also clear that tiltIndicatorAfter/output/result.csv is what we send to banks. 

In summary, with this sequential, modular structure the name of each project reflects its goal, and the relationship with other projects. It also adds the context to understand the contents of its files and folders so we can standardize them. Using standard names makes the project easier to maintain. The explanations in data_prep_v6/README.txt are nice (thanks!) but are hard to maintain -- when we change the name of a file we need to remember to update the documentation.

TODO

I setup an RStudio project that you and I can share. I'll send you the details for you to access it. Once there:

- [ ] Split the data as suggested here.
- [ ] In tiltIndicatorBefore/ ensure you can successfully knit each .Rmd file (step 1 in my comment above).
- [ ] Let me know so I can take over.

We'll repeat the process for tiltIndicatorAfter/. When we do it is up to you. We can certainly work in parallel if @kalashsinghal or @bobresink can take it over from you.

**Comment by Tilmon** [comment]
@maurolepore thanks for your input! Let's discuss this with the rest of the team in today's meeting that @bobresink scheduled and then agree on the next steps.

**Comment by Tilmon** [comment]
Hi @maurolepore, thanks for the links! I had a look at the website, but leave the deep dive in the whole book to the software developers :) 
Closing the issue now as suggested.

**Comment by Tilmon** [comment]
Superseeded by 

- [Re-factor tilt input data prep tiltIndicatorBefore#429](https://github.com/2DegreesInvesting/tiltIndicator/issues/429) @kalashsinghal 
- [Re-factor data output prep tiltIndicatorAfter#427](https://github.com/2DegreesInvesting/tiltIndicator/issues/427) @bobresink
