### ISSUE TITLE
Include `isic_4digit` column at product level for `sector_profile` and `sector_profile_upstream` indicators

### ISSUE THREAD

**Issue by kalashsinghal** [2DegreesInvesting/tiltIndicator#631]
Dear @maurolepore 

I noticed that the final product level outputs of `sector_profile` and `sector_profile_upstream` indicators exclude the `isic_4digit` column which is an input to tiltIndicator. Please update the code so that it will now also output the `isic_4digit` column for both of them.

Please note that the name of the column is `input_isic_4digit` for `sector_profile_upstream`. 

I am not sure whether this column can also be added using this method mentioned in this article: https://2degreesinvesting.github.io/tiltIndicator/articles/extending-outputs.html. If it can then please update. Thanks!

**Comment by maurolepore** [comment]
@kalashsinghal this duplicates https://github.com/2DegreesInvesting/tiltIndicatorAfter#79.

From the perspective of tiltIndicator, this issue was done a long time ago. You can use `rowid` to pass any column from the input to the output of tiltIndicator functions. If you want a function that outputs specific columns, then you can create that function in tiltIndicatorAfter and I'm already working on a PR that does just that. See https://github.com/2DegreesInvesting/tiltIndicatorAfter/issues/79#issuecomment-1830017388
