### ISSUE TITLE
`emissions/sector_profile()` at product level should preserve unmatched products, filling with `NA`s

### ISSUE THREAD

**Issue by AnneSchoenauer** [2DegreesInvesting/tiltIndicator#657]
**Context**
I know we decided that if the company produces a product that cannot be matched, that we exlcuded it from the analysis. However, if you now look at the emission_profile results, the results only hold for the products that we were able to match with ecoinvent. I think out of transparency, we do need also a NA section here. Especially because of this ticket here, we will have a NA in the emission_profile anyway. https://github.com/2DegreesInvesting/tiltIndicator/issues/638. The same also holds for the sector profiles.

**Concrete this means for the emission profile**
``` r
# Load necessary library
library(dplyr)
#> 
#> Attache Paket: 'dplyr'
#> Die folgenden Objekte sind maskiert von 'package:stats':
#> 
#>     filter, lag
#> Die folgenden Objekte sind maskiert von 'package:base':
#> 
#>     intersect, setdiff, setequal, union

# Define the company's products and their emission profiles
products <- data.frame(
  product_id = 1:4,
  emission_profile = c("high", "medium", NA, NA)
)

# Calculate the emission share for each category
emission_share <- products %>%
  group_by(emission_profile) %>%
  summarize(count = n()) %>%
  mutate(share = count / nrow(products))

# Replace NA in emission_profile with 'no_emission'
emission_share$emission_profile[is.na(emission_share$emission_profile)] <- 'NA'

# View the emission share
print(emission_share)
#> # A tibble: 3 × 3
#>   emission_profile count share
#>   <chr>            <int> <dbl>
#> 1 high                 1    0.25
#> 2 medium               1    0.25
#> 3 NA                   2    0.5
```

<sup>Created on 2024-01-04 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Please note the above reprex also holds for the sector_profiles. 

For me there are the following questions now: 
- [ ] Location of Changes:
Could you please identify where in the process the changes should be implemented. Currently, products without a match in EcoInvent (referred to as 'NAs') are removed in the 'tiltIndicatorBefore' package. I think however, that we should consider altering the 'tiltIndicator' package. My suggestion would be to bring back all products from Europages and calculate the risk_categories (now profiles ) and profile_shares, including those products that lack an emission or sector profile. What do you think @maurolepore and @kalashsinghal?
- [ ] Creation of an output table? Would it help you to see how the output table should then look like if we implemented the NAs? I could then make it up so that you understand what the end-goal would be. 
- [ ] @Tilmon how do we do this with the upstream profiles? It works a bit different here I think and didn't find a good solution. Could you please also think about this and let me know.

**Comment by maurolepore** [comment]
@AnneSchoenauer, 

I explored the code to try understand the current behavior an your request. 

I think you explanation and reprex is a good start but I need to write them for myself to make sure I understand. 

## Current behavior

The current behaviour was mainly introduced via #393 ([search for #393 on GitHub](https://github.com/search?q=repo%3A2DegreesInvesting%2FtiltIndicator%20%22%23393%22&type=code):

* If a company matches some product, the output has no `NA`. Unmatched products are dropped.
* If a company matches no product, the output has `NA` in all columns except `companies_id` and `clustered`.

For example, here I show this with `emissions_profile()` but the same goes for all other indicators:

``` r
library(tidyverse)
devtools::load_all()
#> ℹ Loading tiltIndicator

options(width = 500)

# One of the products can be matched
companies <- example_companies(!!aka("uid") := c("matched", "unmatched"))
companies
#> # A tibble: 2 × 8
#>   activity_uuid_product_uuid companies_id clustered sector subsector tilt_sector tilt_subsector type 
#>   <chr>                      <chr>        <chr>     <chr>  <chr>     <chr>       <chr>          <chr>
#> 1 matched                    a            a         total  energy    a           a              ipr  
#> 2 unmatched                  a            a         total  energy    a           a              ipr

ecoinvent_products <- example_products(!!aka("uid") := c("matched"))
ecoinvent_products
#> # A tibble: 1 × 5
#>   activity_uuid_product_uuid tilt_sector unit  isic_4digit co2_footprint
#>   <chr>                      <chr>       <chr> <chr>               <dbl>
#> 1 matched                    a           a     '1234'                  1

# The output has no `NA`. Unmatched products are dropped.
result <- emissions_profile(companies, ecoinvent_products)

result |> unnest_product()
#> # A tibble: 6 × 7
#>   companies_id grouped_by       risk_category profile_ranking clustered activity_uuid_product_uuid co2_footprint
#>   <chr>        <chr>            <chr>                   <dbl> <chr>     <chr>                              <dbl>
#> 1 a            all              high                        1 a         matched                                1
#> 2 a            isic_4digit      high                        1 a         matched                                1
#> 3 a            tilt_sector      high                        1 a         matched                                1
#> 4 a            unit             high                        1 a         matched                                1
#> 5 a            unit_isic_4digit high                        1 a         matched                                1
#> 6 a            unit_tilt_sector high                        1 a         matched                                1

result |> unnest_company()
#> # A tibble: 18 × 4
#>    companies_id grouped_by       risk_category value
#>    <chr>        <chr>            <chr>         <dbl>
#>  1 a            all              high              1
#>  2 a            all              medium            0
#>  3 a            all              low               0
#>  4 a            isic_4digit      high              1
#>  5 a            isic_4digit      medium            0
#>  6 a            isic_4digit      low               0
#>  7 a            tilt_sector      high              1
#>  8 a            tilt_sector      medium            0
#>  9 a            tilt_sector      low               0
#> 10 a            unit             high              1
#> 11 a            unit             medium            0
#> 12 a            unit             low               0
#> 13 a            unit_isic_4digit high              1
#> 14 a            unit_isic_4digit medium            0
#> 15 a            unit_isic_4digit low               0
#> 16 a            unit_tilt_sector high              1
#> 17 a            unit_tilt_sector medium            0
#> 18 a            unit_tilt_sector low               0



# None of the products can be matched
companies <- example_companies(!!aka("uid") := c("unmatched"))
companies
#> # A tibble: 1 × 8
#>   activity_uuid_product_uuid companies_id clustered sector subsector tilt_sector tilt_subsector type 
#>   <chr>                      <chr>        <chr>     <chr>  <chr>     <chr>       <chr>          <chr>
#> 1 unmatched                  a            a         total  energy    a           a              ipr

# The output has `NA` in all columns except `companies_id` and `clusetered`
result <- emissions_profile(companies, ecoinvent_products)

result |> unnest_product()
#> # A tibble: 1 × 7
#>   companies_id grouped_by risk_category profile_ranking clustered activity_uuid_product_uuid co2_footprint
#>   <chr>        <chr>      <chr>                   <dbl> <chr>     <chr>                              <dbl>
#> 1 a            <NA>       <NA>                       NA a         <NA>                                  NA

result |> unnest_company()
#> # A tibble: 1 × 4
#>   companies_id grouped_by risk_category value
#>   <chr>        <chr>      <chr>         <dbl>
#> 1 a            <NA>       <NA>             NA
```

## New requirement

If I understand correctly the new requirement is the the output should preserve all of the products associated to each company. Those that don't match will just get `NA` in all columns except `companies_id`, `activity_uuid_product_uuid` (so that we know which product it is) and `clustered` (at product-level).

TODO: reprex

## Answering your questions

* a01. *Location of changes*. The current behavior is implemented in tiltIndicator so we certainly need changes here. I'm not sure what happens in tiltIndicatorBefore but if it currently drops some products surely we also need changes there.
* a02. *Creation of an output tables*. Not for now. The most useful way to express a requirement is via a reprex because it's precise and it's easy to turn into a failing test, then into the new code that will eventually make the test pass. A generic reprex as yours is a great start, but here I aim to turn it into a specific reprex that uses tiltIndicator code. With a few iterations of discussion I'm sure we'll get there.
* a03. **If possible** it would be great to come up with a requirement that we can apply consistently to all indicators -- as we currently do. Currently the logic to handle no-matches is likely the most complicated part of tiltIndicator -- meaning we're spending most of our time and money dealing with products that don't match. Making it different for different indicators will make it even more complicated, so more error prone and expensive :-(.

**Comment by Tilmon** [comment]
Hi @maurolepore , @AnneSchoenauer , 
I have a few comments on what you wrote @maurolepore . I hope my comments don't hijack the conversation you and @AnneSchoenauer are having :) 

> If I understand correctly the new requirement is that the output should preserve all of the products associated to each company. 

That's also my understanding. 

> Those that don't match will just get NA in all columns except companies_id, activity_uuid_product_uuid and clustered (at product-level). Because activity_uuid_product_uuid and clustered exist only in the output at product level, the new requirement

I would assume that those that don't match would also get NA in the column activity_uuid_product_uuid, as there is no matched uuid we can show there. Or am I missing something here? 

> does not affect the output at company level.

I believe it should also affect company-level output. As the share of products with the value NA should be shown. I.e. risk_category = NA, risk_share = (number of clustered without matched uuid / all clustered). 

> If possible it would be great to come up with a requirement that we can apply consistently to all indicators -- as we currently do. 

Valid point! Can we treat NAs just as a separate benchmark that is shown (i) either for all results always, even if risk_share(NA) = 0 or (ii) that is only shown if there are unmatched products, i.e. risk_share(NA) > 0

Curious to hear your thoughts @AnneSchoenauer and @maurolepore

**Comment by AnneSchoenauer** [comment]
Dear all, 

thanks a lot for this. I think you understood the problem very well @maurolepore. Here are some comments and addtions. 

**Need for an NA category on the company level when calculating the `shares`.** 
The only thing is that we do need to add a new risk_category which is NA. So the outputs in the company level would look like I had it in my reprex: 

> > `# View the emission share
> print(emission_share)
> #> # A tibble: 3 × 3
> #>   emission_profile count share
> #>   <chr>            <int> <dbl>
> #> 1 high                 1    0.25
> #> 2 medium               1    0.25
> #> 3 NA                   2    0.5`

This means that in your code it says: 

> # NEW REQUIREMENT: Nothing to add?
That this is not true. We would need to add it. In your specific context the company would produce two products - one which has a high risk category and one which is not able to be matched. Therefore on the company level it would have the profile (high = 0.5, medium = 0, low = 0 and NA = 0.5). 

With this regard: 
Specific question to @Tilmon
You wrote: 

> If possible it would be great to come up with a requirement that we can apply consistently to all indicators -- as we currently do.
> 
> Valid point! Can we treat NAs just as a separate benchmark that is shown (i) either for all results always, even if risk_share(NA) = 0 or (ii) that is only shown if there are unmatched products, i.e. risk_share(NA) > 

Can you tell me what you meant with this? Or create a little reprex not quite sure. 

Also @Tilmon I think you are right with that the output tables will change. However, I guess that this is specifically for the tiltIndicatorAfter which then makes sure that the output tables has the changes included imo. 

**Does this hold for other indicators?**
Good news this would hold also for the sector profiles. But please note that it doesnt hold for the upstream profiles.

**Location**
@kalashsinghal, Mauro wrote: 

a01. Location of changes. The current behavior is implemented in tiltIndicator so we certainly need changes here. I'm not sure what happens in tiltIndicatorBefore but if it currently drops some products surely we also need changes there.

Could you please tell us if the non-matched products are filtered out in the tiltIndicatorpackage or what's happening with them?

**Comment by kalashsinghal** [comment]
> a01. Location of changes. The current behavior is implemented in tiltIndicator so we certainly need changes here. I'm not sure what happens in tiltIndicatorBefore but if it currently drops some products surely we also need changes there.

> Could you please tell us if the non-matched products are filtered out in the tiltIndicatorpackage or what's happening with them?
@AnneSchoenauer @maurolepore Yes I have dropped the products which have NA in `activity_uuid_product_uuid` from the `emissions_profile_any_companies` dataset. I will add them back after this issue is resolved in tiltIndicator. I will create a separate ticket for this task. Is it ok?

**Comment by Tilmon** [comment]
@kalashsinghal to create a separate ticket for himself and @maurolepore to finish this ticket.

**Comment by Tilmon** [comment]
_Note_: As discussed in the tech sprint (2024-02-13), this issue DOES NOT applies to the upstream indicators. cc' @maurolepore @AnneSchoenauer

**Comment by kalashsinghal** [comment]
Dear @maurolepore @AnneSchoenauer @Tilmon 

I have added the products which have `NA` in `activity_uuid_product_uuid` using this [PR](https://github.com/2DegreesInvesting/tiltIndicatorBefore/pull/95) for both emission and sector profile. These three files are affected by this change:
1. emissions_profile_any_companies_ecoinvent.csv
2. sector_profile_companies.csv
3. sector_profile_upstream_companies.csv

These three files will now have all the companies whose products are not matched with Ecoinvent. I have uploaded the new files in this [folder](https://drive.google.com/drive/folders/1AbSGCGFVcRM3zLfPg5FdwScTRRaCbIws). You can also review the new files through the [README](https://github.com/2DegreesInvesting/tiltIndicatorBefore?tab=readme-ov-file#output-files-from-tiltindicatorbefore) file of tiltIndicatorBefore. You can use these new files to run the whole tiltWorkflow after work on this PR gets completed.

Please note that due to lack of time (I am going on holidays), I could not ask for a review of the data change, however feel free to review the new files and create issues separately for further development.

**Comment by maurolepore** [comment]
Relates to https://github.com/2DegreesInvesting/tiltIndicatorAfter/issues/153

**Comment by maurolepore** [comment]
The case for unmatched products is alread done for both the `emissions*()` and `sector*()` funtions ([changelog](https://2degreesinvesting.github.io/tiltIndicator/news/index.html)).
