### ISSUE TITLE
Review Physical Risk indicator code and assess level of maturity

### ISSUE THREAD

**Issue by Tilmon** [2DegreesInvesting/tiltIndicator#767]
Hi @kalashsinghal, 

can you please review the physical risk indicator code and assess the level of maturity. You can find detailed documentation [here](https://drive.google.com/file/d/1HUXv36s0Ch3Li77GGzoWTkHNAahA21RI/view?usp=drive_link).

In essence, the indicator calculates physical risk exposure on company-level (no product-level results), based on a company's location. For that, the indicator

- should rank each company acc. to their exposure per extreme weather event
- should output results in a heatmap per extreme weather event (and a rank per company in the output file)
- Note: sector-specific weights were planned but never developed. So you can ignore that component from the documenation for now. 

For more information, please refer to the documentation. 

Thanks!

Pls check out Linda's files [here](https://drive.google.com/drive/u/0/folders/1ReRmVa4Uazc102waSuQUzQiRdI1tP1gR):

**Comment by kalashsinghal** [comment]
@Tilmon I assessed the Physical risk code and came to the conclusion that the code still needs a lot of improvements. Currently, the code is non-functional. These are the improvements we need to work on:

1. Resolve hidden bugs.
2. Write unittests so that resolved bugs won't appear again.
3. Convert current scripts and data into an R package.
4. Document each function and process.

According to my judgement, Physical risk code needs 8-9 days time to be considered prototype-ready.
