### ISSUE TITLE
Estimate Effort required to build functioning & documented prototype for PR indicator

### ISSUE THREAD

**Issue by Tilmon** [2DegreesInvesting/tiltIndicator#773]
Hi @kalashsinghal , 

please identify what still needs to be done for PR indicator and estimate effort that is required. 

Thanks!

**Comment by kalashsinghal** [comment]
@Tilmon I assessed the Physical risk code and came to the conclusion that the code still needs a lot of improvements. Currently, the code is non-functional. These are the improvements we need to work on:

1. Resolve hidden bugs.
2. Write unittests so that resolved bugs won't appear again.
3. Convert current scripts and data into an R package.
4. Document each function and process.

According to my judgement, Physical risk code needs 8-9 days time to be considered prototype-ready.
